/**
  * mutation的常量字符串配置
  * @type {string}
*/

export const SET_FIRSTVISIT='SET_FIRSTVISIT';
export const SET_SCROOLLREFRESH='SET_SCROOLLREFRESH';
export const SET_CLASSIFYID='SET_CLASSIFYID'
export const SET_CATEGORY='SET_CATEGORY'
export const SET_SETVIEWDIRECTION='SET_SETVIEWDIRECTION'
